---
- name: Install Looking Glass dependencies on all servers
  hosts: lookingglass
  become: yes
  tasks:
    # Install required packages
    - name: Install Looking Glass dependencies
      ansible.builtin.dnf:
        name:
          - httpd
          - mod_ssl
          - php
          - php-fpm
          - php-posix
          - git
          - traceroute
          - mtr
          - iperf3
          - firewalld
          - python3-firewall
        state: present

    # Start and enable services
    - name: Start and enable services
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - firewalld
        - httpd
        - php-fpm

    # Configure firewall
    - name: Configure firewall services
      ansible.builtin.firewalld:
        service: "{{ item }}"
        permanent: yes
        state: enabled
        immediate: yes
      loop:
        - ssh
        - http
        - https

    - name: Configure firewall for iperf3
      ansible.builtin.firewalld:
        port: 5201/tcp
        permanent: yes
        state: enabled
        immediate: yes

    # Configure MTR for Looking Glass
    - name: Check if MTR capabilities are already set
      ansible.builtin.shell: getcap {{ item }} | grep -q cap_net_raw
      loop:
        - /usr/sbin/mtr
        - /usr/sbin/mtr-packet
      register: mtr_caps_check
      failed_when: false
      changed_when: false

    - name: Set capabilities on MTR binaries
      ansible.builtin.command: setcap cap_net_raw+ep {{ item.item }}
      loop: "{{ mtr_caps_check.results }}"
      when: item.rc != 0
      ignore_errors: yes

    - name: Create MTR symlinks for Looking Glass
      ansible.builtin.file:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        state: link
        follow: no
      loop:
        - { src: /usr/sbin/mtr, dest: /usr/local/bin/mtr }
        - { src: /usr/sbin/mtr-packet, dest: /usr/local/bin/mtr-packet }
      ignore_errors: yes

    # Verify installation
    - name: Verify network tools are working
      ansible.builtin.command: "{{ item }}"
      loop:
        - ping -c 1 8.8.8.8
        - traceroute -m 5 8.8.8.8
        - mtr --report --report-cycles 1 8.8.8.8
      register: network_test
      changed_when: false

    - name: Display installation summary
      ansible.builtin.debug:
        msg: "{{ inventory_hostname }}: Dependencies installed and services started"